### PR TITLE
Issue 24 - Added load callback on get()

### PR DESCRIPTION
**Pull request by ermicioi**

### CODE REVIEW

**Comment by HQarroum** [comment]
Hi @ermicioi, thanks for your pull request. I reviewed it but I'm bothered by something. In your implementation, a `.get()` operation could potentially result in a call to `.put()` which means that an initial read operation would ultimately cause a mutation of the underlying cache storage.

Having a read operation triggering a write is not recommended and does not really make sense to me from an API perspective.  Also, if the callback function does not (for some reason) return a value, it means that we would put in the cache an `undefined` value.

I understand your requirement but I believe given the small amount of changes required that it would be better to wrap the `.get ()` call in your code and let the core stay minimalist at the `Cache` module level. Let me know what you think.

**Comment by ermicioi** [comment]
1. This was intention, in case the cache does not have a key, then it invoke callback in order to get the required data and put it to cache. This approach will free client to have everywhere an if/else statement in the code.
```
var x = cache.get('myKye');
if (!x) {
  x = computeData();
  cache.put(x);
}
```
can become
```
var x = cache.get('myKey', function() {
  return computeData();
});
```
User will be able to use the old approach, so it is kind of sugar.

2. Does user can do `cache.put(undefined)`? If yes, then it is Ok callback to return undefined, this is already to user to define which value to be returned.
A problem here is that if callback return undefined then the data load will happen always.

3. Sure the wrapper can be done, I just proposed this to be part of core as I am quite sure it will benefic and will allow fluent API.

**Comment by ermicioi** [comment]
@HQarroum

1. any idea how to fix the build. Looks like it failed not because of code.
2. what is your answer regarding the addition? Will it pass?

**Comment by HQarroum** [comment]
Hi @ermicioi, sorry for the delay I've been travelling a lot recently. Let me until this week-end to have a look at your PR in order to integrate it.

The build seems to fail because version 6 of Node.js is part of the build steps and is too old to run the test framework, I'll fix that as well.

**Comment by ermicioi** [comment]
Any update on that?

**Comment by HQarroum** [comment]
Hi @ermicioi, sorry for the delay. I took your PR, modified it a bit and integrated it into the next release `1.1.3` which I just published. I'll close this PR and let me know if I can close your issue. Thanks for your contribution !

**Pull request closed without merging**
